### PR TITLE
Create cleanup.sh

### PR DESCRIPTION
**Pull request by srowhani**

### CODE REVIEW

**Review by awaisabir — APPROVED** [review]
This is insane! Amazing work

**Review by Jasonjys — APPROVED** [review]
looks great

**Comment by Angus-Leung** [comment]
I agree with above changes, this will greatly improve the quality of the codebase.

**Comment by awaisabir** [comment]
@Angus-Leung This might just be the game-changer ⚡️

**Comment by srowhani** [comment]
@bl - 
I appreciate the work you've done for this project, but I feel as if you're slowing down the progress of development. To others who feel the same, give this post a thumbs up if you'd like to remove @bl from the repo.

**Comment by bl** [comment]
Thanks for your thoughtful and wonderful interest in improving the dotfiles project.

Unfortunately we believe that your changes don't align with the ethos of this project and have decided to close this issue.

**Also:** This wouldn't work because `.vimrc` sources `.vim` files. I don't think sourcing bash script files will run them within the context of a shell prompt.

**Pull request closed without merging**
